source 'https://cdn.cocoapods.org/'

def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

# Explicitly disable new architecture until all dependencies are updated
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

# Use it to require both react-native's and this package's scripts:
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

require_relative './mendix_utils'

deployment_target = "15.5"
platform :ios, deployment_target

prepare_react_native_project!
generate_mendix_delegate
setupInfoDevPlist

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

setup_permissions([
  'Camera',
  'PhotoLibrary',
  'LocationWhenInUse',
])

def common_pods
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # RN development pods
  config = use_native_modules!

  xcconfig_file = "./Config/config.xcconfig"
  xcconfig = Xcodeproj::Config.new(xcconfig_file)

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  # RN pods end

  # Manually linked dependencies
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  # Third party dependencies of dependencies
  pod 'IQKeyboardManager'

  # The pods listed in this section are essential for the application to function correctly.
  # These pods are added by Native Builder UI (NBUI) and should not be modified under any circumstances.
  # Do not make any changes to the pods in this section.
  # REQUIRED PODS START
# Required MendixNative dependency
  pod 'SSZipArchive'
  # REQUIRED PODS END
end

target 'nativeTemplate' do
  generate_pod_dependencies
  use_native_modules!
  common_pods
  # Intentionally left empty
end

target 'dev' do
  generate_pod_dependencies
  use_native_modules!
  common_pods
  # Intentionally left empty
end

post_install do |installer|
  config = use_native_modules!
  react_native_post_install(
    installer,
    config[:reactNativePath],
    :mac_catalyst_enabled => false,
    # :ccache_enabled => true
  )

# Fix fmt 11.0.2 consteval compilation error with Xcode 26.4+
  fmt_base = File.join(installer.sandbox.root, 'fmt', 'include', 'fmt', 'base.h')
  if File.exist?(fmt_base)
    content = File.read(fmt_base)
    patched = content.gsub(/^#\s*define FMT_USE_CONSTEVAL 1$/, '# define FMT_USE_CONSTEVAL 0')
    if patched != content
      File.chmod(0644, fmt_base)
      File.write(fmt_base, patched)
      puts ":white_check_mark: Patched fmt/base.h: FMT_USE_CONSTEVAL set to 0"
    end
  end

  installer.pods_project.build_configurations.each do |config|
    config.build_settings['ENABLE_BITCODE'] = 'NO'
    config.build_settings['OTHER_LDFLAGS'] ||= ['$(inherited)']
    if config.name == "Debug"
      config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
    end
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == "React"
        if config.name == "ReleaseDevApp"
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << "DEBUG=1"
        end
      end
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
      # Specify 'Swift Version: 5.0' for resolving archieve errors.
      if target.name == 'react-native-video'
          config.build_settings['SWIFT_VERSION'] = '5.0'
      end
      if target.name == 'VisionCamera'
          config.build_settings['SWIFT_VERSION'] = '5.2'
      end
    end
  end
  # Ensure deployment_target is set correctly for all projects
  installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
          end
      end
      project.build_configurations.each do |bc|
          bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
      end
  end
end
